UI_LANGUAGES = {
	"en": {
		"start_msg": "Hello!",
		"settings_btn": "⚙️Settings",
		"settings_msg": "⚙️Settings:",
		"back_btn": "🔙Back", 
		"audio_btn": "🔈Audio",
		"audio_settings_msg": "🔈Audio settings:",
		"speech_is_slow_btn": ["Slow speech: 🚫", "Slow speech: ✅"],
		"speech_is_slow_msg": ["⚠️\"Slow speech\" is enabled!", "⚠️\"Slow speech\" is disabled!"],
		"language_btn": "🌐Language",
		"language_settings_msg": "🌐Interface language:",
		"installed_lang_msg": "⚠️English language installed!",
		"back_to_menu_msg": "🔸Main menu:",
		"scaning_msg": "Scanning...",
		"translate_ibtn": "Translate",
		"long_message": "Text is too long!",
		"choose_lang_msg": "Choose language:",
		"text_not_found": "⚠️Text not found! Please try again!",
		"record_audio": "⚠️Voice is being recorded, please wait!"
	},
	"ru": {
		"start_msg": "Привет!",
		"settings_btn": "⚙️Настройки",
		"settings_msg": "⚙️Настройки:",
		"back_btn": "🔙Назад", 
		"audio_btn": "🔈Аудио",
		"audio_settings_msg": "🔈Настройки звука:",
		"speech_is_slow_btn": ["Медленный речь: 🚫", "Медленный речь: ✅"],
		"speech_is_slow_msg": ["⚠️\"Медленная речь\" включен!", "⚠️\"Медленная речь\" отключен!"],
		"language_btn": "🌐Язык",
		"language_settings_msg": "🌐Язык интерфейса:",
		"installed_lang_msg": "⚠️Русский язык установлен!",
		"back_to_menu_msg": "🔸Главное меню:",
		"scaning_msg": "Сканирование...",
		"translate_ibtn": "Перевести",
		"long_message": "Текст слишком длинный!",
		"choose_lang_msg": "Выберите язык:",
		"text_not_found": "⚠️Текст не найден! Пожалуйста, попробуйте еще раз!",
		"record_audio": "⚠️Голос записывается, подождите пожалуйста!"
	},
	"uz": {
		"start_msg": "Salom!",
		"settings_btn": "⚙️Sozlamalar",
		"settings_msg": "⚙️Sozlamalar:",
		"back_btn": "🔙Orqaga",
		"audio_btn": "🔈Audio",
		"audio_settings_msg": "🔈Audio sozlamalari:",
		"speech_is_slow_btn": ["Sekin nutq: 🚫", "Sekin nutq: ✅"],
		"speech_is_slow_msg": ["⚠️\"Sekin nutq\" yoqildi!", "⚠️\"Sekin nutq\" o'chirildi!"],
		"language_btn": "🌐Til",
		"language_settings_msg": "🌐Interfeys tili:",
		"installed_lang_msg": "⚠️O'zbek tili o'rnatildi!",
		"back_to_menu_msg": "🔸Asosiy menyu:",
		"scaning_msg": "Skanerlash...",
		"translate_ibtn": "Tarjima",
		"long_message": "Matn juda uzun!",
		"choose_lang_msg": "Tilni tanlang:",
		"text_not_found": "⚠️Matn topilmadi! Iltimos, yana bir bor urinib ko'ring!",
		"record_audio": "⚠️Ovoz yozilmoqda, iltimos kuting!"
	}
}

TRANSLATE_LANGUAGES = {
    "en": "🇬🇧ENG",
    "ru": "🇷🇺RUS",
    "uz": "🇺🇿UZB",
    "tr": "🇹🇷TUR",
    "de": "🇩🇪DEU",
    "es": "🇪🇸ESP",
    "it": "🇮🇹ITA",
    "fr": "🇫🇷FRA",
    "hi": "🇮🇳IND",
    "zh-cn": "🇨🇳CHN",
    "ja": "🇯🇵JPN",
    "ko": "🇰🇷KOR"
}