# Generated by Django 4.0.3 on 2022-04-04 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.PositiveIntegerField(unique=True)),
                ('first_name', models.CharField(max_length=64, null=True)),
                ('username', models.CharField(max_length=32, null=True)),
                ('language_code', models.CharField(max_length=10)),
                ('ui_language', models.CharField(max_length=10)),
                ('user_status', models.CharField(choices=[('active', 'active'), ('deleted', 'deleted'), ('blocked', 'blocked')], default='active', max_length=10)),
                ('speech_is_slow', models.BooleanField(default=False)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['time_create', 'time_update'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.PositiveIntegerField(unique=True)),
                ('src', models.CharField(max_length=20)),
                ('dest', models.CharField(max_length=20)),
                ('message_text', models.TextField(max_length=4096)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botapp.botuser')),
            ],
        ),
    ]
