# Generated by Django 4.0.3 on 2022-04-07 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0003_audiomessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioMessage',
        ),
    ]
